### ISSUE TITLE
Webm playback  issue

### ISSUE THREAD

**Issue by TLCPlusPlus** [rebane621/e621-android#1]
At the end of any video, it won't loop with the error "cant play this video". Even though I tap on ok, the message spams forever until my device lags, forcing me to close it. My device is a HTC One A9 on 6.0.1 (htc unlocked)

**Comment by rebane621** [comment]
I know that this happens, though I'm currently not sure why.
Might be because I played with the code a bit, but can't see the Problem :/

**Comment by TLCPlusPlus** [comment]
Issue is confirmed resolved in latest version.
