### ISSUE TITLE
Support large images

### ISSUE THREAD

**Issue by DarkDaskin** [rebane621/e621-android#11]
Large images are not visible.

Logcat shows the following error:
`W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2256x1125, max=2048x2048)`

For even bigger images the application tells that it does not support it and shows the preview instead.

You can try to use some other component for displaying images. Quick googling points to this one: [Subsampling Scale Image View](https://github.com/davemorrissey/subsampling-scale-image-view). It seems to support the same features as TouchImageView, but with large image support.

**Comment by DarkDaskin** [comment]
Tried that library, it works quite well. It does not support GIFs, so the existing component still needs to be used for them.
Few glitches still remain, I will send a pull request after I fix them.

**Comment by rebane621** [comment]
I think I've successfully implemented this.
Thanks for the suggestion
