### ISSUE TITLE
SaveAs doesn't work

### ISSUE THREAD

**Issue by TLCPlusPlus** [rebane621/e621-android#2]
I get a error in any directory saying can't save file: /sdcard/file_here EACESS: (permission denied) 
I'm on HTC One A9 on 6.0.1, not rooted.

**Comment by rebane621** [comment]
Seems to be part of new security measurements in Android 6+.
I'll try to implement a confirm dialogue like mentioned here http://stackoverflow.com/questions/33139754/android-6-0-marshmallow-cannot-write-to-sd-card

**Comment by rebane621** [comment]
should be fixed with the latest update. You'll get a permission prompt you'll have to confirm.
